## python program

this is my first python program

In [27]:
print("hello world!")

hello world!

In [28]:
import sys

In [29]:
print(sys.version)

3.13.1 (v3.13.1:06714517797, Dec  3 2024, 14:00:22) [Clang 15.0.0 (clang-1500.3.9.4)]

### errors

In [30]:
frint("hello world!")

NameError: name 'frint' is not defined

## types

<ul>you can determine the type of a value using the <b>type</b> keyword e.g. <b>type(11)</b></ul>
<ul>you can also cast types</ul>
<ul>boolean types are <b>uppercase</b> in python</ul>

In [ ]:
type(11)

In [ ]:
float(2)

In [ ]:
int(1.5)

In [ ]:
str(2.2)

## expressions & variables

<ul>python performs <strong>multiplication</strong> before <strong>addition</strong></ul>

In [ ]:
x = 30 + 20 - 40 
print(x) # x is the variable

In [ ]:
name = "is the total"
y = 4
x = 30 + 20
print(x + y, name, "hello")

## strings

<ul><b>len</b> to obtain the length of a string</ul>
<ul><b>\</b> is used as escape sequence</ul>

<ul><b>\n</b> new line</ul>
<ul><b>\t</b> new tab</ul>

In [ ]:
name = "Moyosoore Okeyode"

In [ ]:
# slicing
first_part = name[0:4]
print(first_part)
print(name[0:4],name[-7:-1])

In [ ]:
name = "Michael Jackson"
print(name)

### string methods

In [ ]:
name_upper = name.upper()
print(name_upper)

In [ ]:
name_replace = name.replace("Michael", "Moyo")
print(name_replace)

In [ ]:
name_substring = name_replace.find("Moyo")
print(name_substring)

In [ ]:
# string interpolation (f-strings)
print(f"This is string interpolation for {name_replace}")
# ---- OR ----
print("This is string interpolation for {}".format(name_replace))

In [ ]:
# raw strings (r-strings)
print("right way: ",r"C:\sooreoluwa\hello\how are you")

print("wrong way: ","C:\sooreoluwa\hello\how are you")

## Tuples

<ul>tuples are ordered sequences.</ul>
<ul>the elements are separated with a comma within a parantheses.</ul>
<ul>tuples can have different types.</ul>
<ul>elements in a tuple can be accessed with indexes</ul>
<ul>tuples can be concatenanted</ul>

In [ ]:
tuple1 = (10, "Moyo", 2.2, True)

In [ ]:
nt = (20, ("Moyo", "Soore"), (3,5))

In [ ]:
print(nt[1][1])

## Lists

<ul>tuples are ordered sequences.</ul>
<ul>the elements are separated with a comma within a []</ul>
<ul>List can have different types.</ul>
<ul>elements in a tuple can be accessed with indexes</ul>
<ul>contains different types including list, tuples etc</ul>
<ul>slicing can also be done</ul>
<ul>list are mutable</ul>

In [ ]:
# extending list
l = [0,1,2,3]
l.extend([4]) 
# --- OR ----
l.append(4)

In [ ]:
# mutability
l[0] = 11

In [ ]:
print(l)

In [ ]:
# to delete an element
del(l[0])
print(l)

In [ ]:
# to change a string to a list. nb: every group of characters separated by a space.
# you can specify a delimiter as well.
"hard".split()

In [ ]:
"r,o,c,k".split(",")

In [ ]:
# to clone a list
k = l[:]

In [31]:
print(k)

[1, 2, 3, 4, 4]

## Dictionaries

<ul>dictionaries use keys and values, just like Map</ul>
<ul>curly braces are used to create dictionaries</ul>
<ul>the keys have to immutable and unique</ul>
<ul>values can be immutable, mutable or duplicates</ul>
<ul> <b>in</b> keyword can be used to check the presence of a key</ul>
<ul> .keys() can used to view all the keys</ul>
<ul> .values() can used to view all the keys</ul>

## Set

In [47]:
l = [0,1,2,3,4,4,4,4]
m = [4,5,6,7,8,8,8,8]

x = set(l)
y = set(m)

In [48]:
x.add(5)
x.remove(3)

In [49]:
print(x)
0 in x

{0, 1, 2, 4, 5}

True

In [55]:
z = x & y
print(z)

{4, 5}

In [51]:
x.union(y)

{0, 1, 2, 4, 5, 6, 7, 8}

In [52]:
x.issubset(y)

False

In [53]:
y.issubset(x)

False

In [56]:
z.issubset(x)

True

In [57]:
z.issubset(y)

True

## Conditions and Branching

In [59]:
a = 20

if a > 10:
    print("greater")
else:
    print("lower")

print("hello world")

greater
hello world

In [60]:
# logical operators : or, and, not.

## Loops

In [65]:
range(0,3)

range(0, 3)

In [9]:
squares = ["red", "yellow", "blue",'white','white']

for i in range(0, len(squares)):
    squares[0] = "white"
    print(squares)

['white', 'yellow', 'blue', 'white', 'white']
['white', 'yellow', 'blue', 'white', 'white']
['white', 'yellow', 'blue', 'white', 'white']
['white', 'yellow', 'blue', 'white', 'white']
['white', 'yellow', 'blue', 'white', 'white']

In [10]:
for square in squares:
    print(square)

white
yellow
blue
white
white

In [11]:
# enumerate can be used to obtain the index and element in a list
for i, square in enumerate(squares):
    print(f"{i} : ", square)

0 :  white
1 :  yellow
2 :  blue
3 :  white
4 :  white

In [3]:
squares2 = ["white","red", "yellow", "blue", "white", "white", "pink"]
new = []
i = 0
while(squares2[i] == "white"):
    new.append(squares2[i])
    i=i+1
print(new)

['white']

## functions

In [6]:
# len to get the length of the items.
# sum to get the total of items.
# sorted(list) does not make changes to the original list, list.sort() can be used to sort items in a list.
# def is used to start a function.

# e.g.

def add(a):
    b = a + 1
    return b

In [7]:
add(2)

3

In [8]:
# multiplication sign can also mean to repeat
# *variableName allows input of various elements

def artistName(*names):
    for name in names:
        print(name)

In [9]:
artistName("Davido", "Wizkid", "Johnny Drille", "Asake")

Davido
Wizkid
Johnny Drille
Asake

## reading files

In [4]:
tweets = open("tweets.json","r")
# w : to write
# r : to read
# a : to append

In [26]:
# using a with statement automatically closes the file.
with open("basics.txt","r") as file1:
    file_stuff = file1.read(1)
    print(file_stuff) 
print(file1.closed)
print(file_stuff)

T
True
T

In [37]:
# using a with statement automatically closes the file.
with open("write.txt","w") as file1:
    file1.write("This is a file that is ambiguous.")
print(file1.closed)

True

In [40]:
lines = ["This is line One.\n", "This is line Two.\n", "This is line Three."]
with open("write.txt","w") as file1:
    for line in lines:
        file1.write(line)

In [41]:
with open("write.txt","a") as file1:
    file1.write("\nThis is line Four.")

In [43]:
# to copy from one file to another.
with open("basics.txt", "r") as readFile:
    with open("write.txt", "a") as writtenFile:
        for line in readFile:
            writtenFile.write(line)

## pandas
used for data analysis

In [47]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-macosx_10_13_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.2-cp313-cp313-macosx_14_0_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-macosx_10_13_x86_64.whl (12.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 26.8 MB/s eta 0:00:0000:010:01
Downloading numpy-2.2.2-cp313-cp313-macosx_14_0_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 24.4 MB/s eta 0:00:0000:01
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.2 pandas-2.2.3 pytz-2024.2 tzdata-2025.1

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
file_path = 'emails.csv'

In [5]:
# saved in a dataframe. a dataframe comprises of rows and columns

df = pd.read_csv(file_path)

In [6]:
# .head() is used to examine the first 5 rows of a dataframe.
df.head()

                       file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

In [60]:
# creating a data frame from a dictionary. the keys corresponds to the column label.
# while the values correspond to the row label.

song = {"Album": ["Morayo"], "Released": ["2024"], "Artist": ["Wizkid"]}

In [61]:
song_df = pd.DataFrame(song)

In [62]:
song_df.head()

    Album Released  Artist
0  Morayo     2024  Wizkid

In [63]:
song_df[["Album"]]

    Album
0  Morayo

In [70]:
# accessing data in a row and column using index
print(df.iloc[0,2])
print(df.iloc[20,2])

Sheryl
Maxwell

In [73]:
# accessing data in a row and column using index and column name
print(df.loc[0,'Phone 1'])
print(df.loc[20,'Phone 2'])

229.077.5154
202-880-0688x7491

In [80]:
# working with data frames
x = df.iloc[0:2, 0:3]

# slicing data frames
y = df.loc[0:2, 'First Name':'Phone 1']

In [90]:
y.head()

,First Name,Last Name,Company,City,Country,Phone 1
0,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154
1,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776
2,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259

In [106]:
# extracting unique characters
len(df["Subscription Date"].unique())

96

In [115]:
# creating a dataframe from another dataframe.
df1 = df[df["Subscription Date"] > "2020-08-24"]

In [116]:
df1.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [118]:
# to save to a new csv
df1.to_csv("new.csv")

## numpy

In [119]:
import numpy as np

In [120]:
a = np.array([1,2,3,4,5])

In [121]:
print(a)

[1 2 3 4 5]

In [122]:
type(a)

numpy.ndarray

In [124]:
# number of element.
a.size

5

In [125]:
# number of array dimension
a.ndim

1

In [127]:
a[0] = 0
print(a)

[0 2 3 4 5]

In [128]:
a[0] = 10000
print(a)

[10000     2     3     4     5]

In [129]:
a[0] = 10
print(a)

[10  2  3  4  5]

In [130]:
a[1:3]

array([2, 3])

In [131]:
a[1:3] = 100,200

In [132]:
print(a)

[ 10 100 200   4   5]

## api

In [3]:
import requests as req

In [4]:
url = 'https://www.ibm.com/'
r = req.get(url)

In [5]:
r.status_code

200

In [7]:
r.headers

{'Content-Security-Policy': 'upgrade-insecure-requests', 'x-frame-options': 'SAMEORIGIN', 'Last-Modified': 'Sun, 26 Jan 2025 16:47:22 GMT', 'ETag': '"29435-62c9eb6b533f0-gzip"', 'Accept-Ranges': 'bytes', 'Content-Type': 'text/html;charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'max-age=600', 'Expires': 'Sun, 26 Jan 2025 17:34:58 GMT', 'X-Akamai-Transformed': '9 27939 0 pmb=mTOE,2', 'Content-Encoding': 'gzip', 'Date': 'Sun, 26 Jan 2025 17:24:58 GMT', 'Content-Length': '28125', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000'}

In [ ]:
# using lambda with map
#  lambda is a an anonymous function, lambda arguments: expression e.g. lambda x: x*x

# instead of
def addF(a,b):
    return a + b

#  we can do
addL = lambda a, b: a + b

addL(3,5)

# with map
numbers = [1,2,3,4,5,6]

cube_numbers = map(lambda x: x * x * x, numbers)